name: Deploy to Dev

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t placemux-backend ./backend

      - name: Deployment Message
        run: echo "PlaceMux deployed to Dev Environment"